### ISSUE TITLE
Improper map string generated for "3-Player" + "Small 2-Ring Hex"

### ISSUE THREAD

**Issue by 1Mill** [DerekPPeterson/ti4-map-generator#3]
An incomplete map string is generated when the options "Number of Players: 3" and "Layout: Small 2-Ring Hex" are selected.

This bug does not appear to be impacted by other options (e.g. star-by-star, Muatt Supernova, etc.) being enabled. 

It appears that the output string only contains ring-1-hex-2 and ring-2-hex-4 through ring-2-hex-7, all other tiles are missing. 

Nevertheless, great tool!

**Comment by DerekPPeterson** [comment]
Thanks for opening the issue!
Caused because the 2-ring map has mecatol at [2,2] rather than [3,3] which meant that the hardcoded list of locations used to generate that string was off-centre.
Fixed, the string should now generate on all map layouts.
