### ISSUE TITLE
Request: Hyper Lane Sector

### ISSUE THREAD

**Issue by Furluge** [DerekPPeterson/ti4-map-generator#4]
Hi there I was just wondering if it would be possible to get a variant of the 5 player warp zone that draws the tiles so it matches the hyperlane sector design. (https://boardgamegeek.com/image/4141274/porkstewjoe) If I'm not mistaking the way it generates the map works perfectly fine with that design, you just put the one hex, for example 26 in this example image. (https://ti4-map-generator.derekpeterson.ca/cgi-bin/ti4-map-generator-cgi.py?image=galaxy_CSPSZH.png) So it's not a major thing but it'd be nice to to visually see it for laying out tiles. Especially since there are some nice tiles out there that can be printed for this. (https://www.thingiverse.com/thing:3867131)

**Comment by DerekPPeterson** [comment]
Unfortunately all of the code relies on the assumption that the tiles can be placed in the hex grid, while the ideal placement of the tile is not aligned.

The layout is functionally the same so I don't think I'll end up getting to this issue anytime soon.
