### ISSUE TITLE
Map String for Balanced and Narrow 4-Player Setup Returning Duplicate Tile; Missing [0,1] tile

### ISSUE THREAD

**Issue by taylorfsteele** [DerekPPeterson/ti4-map-generator#7]
Just noticed that the Map String output for the 4-Player Balanced and Narrow maps have a duplicate tile at the end, and is missing the value for the [0,1] (I think?) tile.

![tiMapIssueGithub](https://user-images.githubusercontent.com/58190950/77449826-d86b0300-6dc8-11ea-9603-27d9e4dc0418.png)

Here it's tile 19 that's duplicated & tile 28 that's missing. From what I can tell it's those same coordinates every time.

Thanks for this great tool! I use this for every game I play.

**Comment by DerekPPeterson** [comment]
fixed
